theme: jekyll-theme-minimal
title: All you need is love...and a good chemical affinity
description: A project exploring chemical affinity and its applications in data analysis
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
